const item = (value) => Object.freeze(value);

export const menuItems = Object.freeze([
  item({
    id: "flat-white",
    category: "coffee",
    categoryLabel: "Кофе",
    name: "Флэт уайт",
    description: "Двойной эспрессо и тонкий слой бархатистого молока.",
    volume: "200 мл",
    price: 290,
    badge: "Хит",
  }),
  item({
    id: "espresso-tonic",
    category: "coffee",
    categoryLabel: "Кофе",
    name: "Эспрессо-тоник",
    description: "Цитрусовый тоник, эспрессо и много льда.",
    volume: "350 мл",
    price: 340,
  }),
  item({
    id: "cappuccino",
    category: "coffee",
    categoryLabel: "Кофе",
    name: "Капучино",
    description: "Сбалансированный эспрессо с воздушной молочной текстурой.",
    volume: "300 мл",
    price: 270,
  }),
  item({
    id: "filter-coffee",
    category: "coffee",
    categoryLabel: "Кофе",
    name: "Фильтр-кофе",
    description: "Сезонное зерно светлой обжарки, заваренное вручную.",
    volume: "250 мл",
    price: 230,
  }),
  item({
    id: "syrniki-salted-caramel",
    category: "breakfast",
    categoryLabel: "Завтраки",
    name: "Сырники с солёной карамелью",
    description: "Нежные сырники, сметана и домашняя солёная карамель.",
    volume: "260 г",
    price: 490,
    badge: "Любимый завтрак",
  }),
  item({
    id: "salmon-brioche",
    category: "breakfast",
    categoryLabel: "Завтраки",
    name: "Бриошь с лососем",
    description: "Слабосолёный лосось, крем-чиз, яйцо и свежая зелень.",
    volume: "240 г",
    price: 620,
  }),
  item({
    id: "shakshuka",
    category: "breakfast",
    categoryLabel: "Завтраки",
    name: "Шакшука",
    description: "Яйца в пряном томатном соусе, фета и ремесленный хлеб.",
    volume: "320 г",
    price: 540,
  }),
  item({
    id: "granola-berries",
    category: "breakfast",
    categoryLabel: "Завтраки",
    name: "Гранола с ягодами",
    description: "Домашняя гранола, греческий йогурт, ягоды и мёд.",
    volume: "280 г",
    price: 430,
  }),
  item({
    id: "almond-croissant",
    category: "bakery",
    categoryLabel: "Выпечка",
    name: "Миндальный круассан",
    description: "Хрустящие слои, миндальный крем и лепестки миндаля.",
    volume: "1 шт.",
    price: 260,
    badge: "Каждое утро",
  }),
  item({
    id: "pain-au-chocolat",
    category: "bakery",
    categoryLabel: "Выпечка",
    name: "Пан-о-шоколя",
    description: "Слоёное тесто на сливочном масле и тёмный шоколад.",
    volume: "1 шт.",
    price: 250,
  }),
  item({
    id: "cinnamon-bun",
    category: "bakery",
    categoryLabel: "Выпечка",
    name: "Булочка с корицей",
    description: "Мягкая сдоба, цейлонская корица и сливочная глазурь.",
    volume: "1 шт.",
    price: 240,
  }),
  item({
    id: "basque-cheesecake",
    category: "bakery",
    categoryLabel: "Выпечка",
    name: "Баскский чизкейк",
    description: "Карамельная корочка и нежная сливочная середина.",
    volume: "140 г",
    price: 390,
  }),
]);
